version: '3.8'

networks:
  wordpress-network:
    driver: bridge
    name: wordpress-network

volumes:
  wordpress-volume:
    name: wordpress-volume
  mysql-volume:
    name: mysql-volume

services:
  wordpress:
    container_name: wordpress
    image: wordpress:6.1.1
    networks:
      - wordpress-network
    volumes:
      - wordpress-volume:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    networks:
      - wordpress-network
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
